Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> Most recent one is a typo?
> 
> c:\b\s\w\ir\k\gn\base\command_line.cc(191): error C2059: syntax error: ')'

The VCINSTALLDIR looks updated in that error log, so I think it's updated to the new SDK, but not positive.

Patch-set: 8
Reviewer: Gerrit User 1000004 <1000004@c360c8e5-7aa8-3905-a7a0-810934766dac>