Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> I don't have a Submit button (as scottmg@chromium.org). Should I be @google? Or should I add myself somewhere?
> 
> ...
> 
> Actually, I don't think I do as @google either.

Pushing from command line I get this... I'm not sure what I need to update for that though.

To https://gn.googlesource.com/gn
 ! [remote rejected]   HEAD -> master (prohibited by Gerrit: ref update access denied)
error: failed to push some refs to 'https://gn.googlesource.com/gn'

Patch-set: 1
Reviewer: Gerrit User 1000004 <1000004@c360c8e5-7aa8-3905-a7a0-810934766dac>
Label: Commit-Queue=0