Update patch set 2
Patch Set 2:

(On Windows, recipes.py says

[99a5655...]c:\src\gn>python infra\recipes.py test train

gn.ci_linux failed:
Traceback (most recent call last):
  File "c:\src\gn\infra\.recipe_deps\recipe_engine\recipe_engine\test.py", line 631, in wrapper
    return (True, test, f(test, *args, **kwargs))
  File "c:\src\gn\infra\.recipe_deps\recipe_engine\recipe_engine\test.py", line 640, in run_worker
    return run_test(test, mode)
  File "c:\src\gn\infra\.recipe_deps\recipe_engine\recipe_engine\test.py", line 259, in run_test
    _UNIVERSE_VIEW.load_recipe(test_description.recipe_name).run_steps,
AttributeError: 'NoneType' object has no attribute 'load_recipe'
...

which makes this more awkward too. But doesn't matter too much, can work on a Linux/Mac machine after testing.)

Patch-set: 2
Reviewer: Gerrit User 1000004 <1000004@c360c8e5-7aa8-3905-a7a0-810934766dac>