Fix gcc compilation by including required header
Compilation with gcc is currently failing with the
following error:
```
error: no template named 'equal_to' in namespace 'std'
```

Change-Id: Ie1a705b97bbbd6bf0615e176af29f9d9a0dc4467