desc_builder.cc: Remove redundant move in return statement
Fixes build with gcc13

../git/src/gn/desc_builder.cc: In member function 'base::Value {anonymous}::BaseDescBuilder::ToBaseValue(const Scope*)':
../git/src/gn/desc_builder.cc:179:21: error: redundant move in return statement [-Werror=redundant-move]
  179 |     return std::move(res);
      |            ~~~~~~~~~^~~~~

Change-Id: I7ee3a9a739f5e8a448279be092036be7f5dee930
Signed-off-by: Khem Raj <raj.khem@gmail.com>