Update patch set 1
Patch Set 1:

> Patch Set 1: Commit-Queue+2
> 
> Petr, do these Mac errors look familiar? (I'll give it another half-hearted retry for now...)
> 
> [39/246] CXX base/values.o
> [40/246] AR base.a
> FAILED: base.a 
> rm -f base.a && libtool -static -o base.a base/callback_internal.o base/command_line.o base/environment.o base/files/file.o base/files/file_enumerator.o base/files/file_path.o base/files/file_path_constants.o base/files/file_util.o base/files/scoped_file.o base/files/scoped_temp_dir.o base/json/json_parser.o base/json/json_reader.o base/json/json_writer.o base/json/string_escape.o base/logging.o base/md5.o base/memory/ref_counted.o base/memory/weak_ptr.o base/sha1.o base/strings/string_number_conversions.o base/strings/string_piece.o base/strings/string_split.o base/strings/string_util.o base/strings/string_util_constants.o base/strings/stringprintf.o base/strings/utf_string_conversion_utils.o base/strings/utf_string_conversions.o base/third_party/icu/icu_utf.o base/timer/elapsed_timer.o base/value_iterators.o base/values.o base/files/file_enumerator_posix.o base/files/file_posix.o base/files/file_util_posix.o base/posix/file_descriptor_shuffle.o base/posix/safe_strerror.o base/strings/string16.o
> error: /b/s/w/ir/cache/macos_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: base/callback_internal.o is not an object file (not allowed in a library)
> error: /b/s/w/ir/cache/macos_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: base/command_line.o is not an object file (not allowed in a library)
> error: /b/s/w/ir/cache/macos_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: base/environment.o is not an object file (not allowed in a library)
> error: /b/s/w/ir/cache/macos_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: base/files/file.o is not an object file (not allowed in a library)

No but I suspect it's because of LTO that was turned on in https://gn.googlesource.com/gn/+/377ad0417d8f7df348fd865e21a0a905daa4b22c. I tested that on Linux but not on macOS which was clearly a mistake.

I'll try to reproduce this locally on my Mac.

Patch-set: 1
Reviewer: Gerrit User 1000002 <1000002@c360c8e5-7aa8-3905-a7a0-810934766dac>