Ignore build warning -Werror=redundant-move
gcc-13 complains with:
error: redundant move in return statement [-Werror=redundant-move]

We cannot fix the code, because both old versions of gcc and the windows
toolchain fails to build.

Change-Id: Iab62336fa37db8fab0dc8acabad0fabfabada0f9