Add missing header for using with std::move
Compilation with gcc is outputing this error:

no member named 'move' in namespace 'std'

Change-Id: Idde1562a9ea9581816b35323a182ddda5c0aea12